// TypeScript Resx model for: /dev/resx-to-ts-json/Resources/TestResources.resx
// Auto generated by resx-to-ts-json (npm package)

export const TestResources: app.resources.TestResources = {
	Test: "Test",
	Feature: {
		resource: "Feature.resource",
		SubFeature: {
			resource: "Feature.SubFeature.resource",
			resource2: "Feature.SubFeature.resource2"
		},
		SubFeature2: {
			resource: "Feature.SubFeature2.resource"
		},
		OtherResource: "Feature.OtherResource"
	},
	Feature2: {
		SubFeature: {
			resource: "Feature2.SubFeature.resource"
		}
	},
	ValueWithSingleQuote: "ValueWithSingleQuote"
}
