// TypeScript Resx model for: /dev/resx-to-ts-json/Resources/TestResources.resx
// Auto generated by resx-to-ts-json (npm package)

export const TestResources: app.resources.TestResources = {
	Test: "TestResources.Test",
	Feature: {
		resource: "TestResources.Feature.resource",
		SubFeature: {
			resource: "TestResources.Feature.SubFeature.resource",
			resource2: "TestResources.Feature.SubFeature.resource2"
		},
		SubFeature2: {
			resource: "TestResources.Feature.SubFeature2.resource"
		},
		OtherResource: "TestResources.Feature.OtherResource"
	},
	Feature2: {
		SubFeature: {
			resource: "TestResources.Feature2.SubFeature.resource"
		}
	},
	ValueWithSingleQuote: "TestResources.ValueWithSingleQuote"
}
