// TypeScript Resx model for: /custom/node-resx-to-typescript/Resources/TestResources.resx
// Auto generated by resx-to-typescript (npm package)

declare module app.resources {
	export class TestResources {
		Test: string;
		Feature: {
			resource: string;
			SubFeature: {
				resource: string;
				resource2: string;
			};
			SubFeature2: {
				resource: string;
			};
			OtherResource: string;
		};
		Feature2: {
			SubFeature: {
				resource: string;
			};
		};
	}
}
